// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewMultiSigRequest struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Pubkeys              [][]byte `protobuf:"bytes,2,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMultiSigRequest) Reset()         { *m = NewMultiSigRequest{} }
func (m *NewMultiSigRequest) String() string { return proto.CompactTextString(m) }
func (*NewMultiSigRequest) ProtoMessage()    {}
func (*NewMultiSigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *NewMultiSigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMultiSigRequest.Unmarshal(m, b)
}
func (m *NewMultiSigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMultiSigRequest.Marshal(b, m, deterministic)
}
func (m *NewMultiSigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMultiSigRequest.Merge(m, src)
}
func (m *NewMultiSigRequest) XXX_Size() int {
	return xxx_messageInfo_NewMultiSigRequest.Size(m)
}
func (m *NewMultiSigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMultiSigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewMultiSigRequest proto.InternalMessageInfo

func (m *NewMultiSigRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NewMultiSigRequest) GetPubkeys() [][]byte {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

type NewMultiSigReply struct {
	RedeemScript         string   `protobuf:"bytes,1,opt,name=redeemScript,proto3" json:"redeemScript,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Pubkeys              [][]byte `protobuf:"bytes,3,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMultiSigReply) Reset()         { *m = NewMultiSigReply{} }
func (m *NewMultiSigReply) String() string { return proto.CompactTextString(m) }
func (*NewMultiSigReply) ProtoMessage()    {}
func (*NewMultiSigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *NewMultiSigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMultiSigReply.Unmarshal(m, b)
}
func (m *NewMultiSigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMultiSigReply.Marshal(b, m, deterministic)
}
func (m *NewMultiSigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMultiSigReply.Merge(m, src)
}
func (m *NewMultiSigReply) XXX_Size() int {
	return xxx_messageInfo_NewMultiSigReply.Size(m)
}
func (m *NewMultiSigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMultiSigReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewMultiSigReply proto.InternalMessageInfo

func (m *NewMultiSigReply) GetRedeemScript() string {
	if m != nil {
		return m.RedeemScript
	}
	return ""
}

func (m *NewMultiSigReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewMultiSigReply) GetPubkeys() [][]byte {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

type NewUnsignedTxRequest struct {
	Receiver             []byte   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	WalletId             string   `protobuf:"bytes,3,opt,name=walletId,proto3" json:"walletId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUnsignedTxRequest) Reset()         { *m = NewUnsignedTxRequest{} }
func (m *NewUnsignedTxRequest) String() string { return proto.CompactTextString(m) }
func (*NewUnsignedTxRequest) ProtoMessage()    {}
func (*NewUnsignedTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *NewUnsignedTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUnsignedTxRequest.Unmarshal(m, b)
}
func (m *NewUnsignedTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUnsignedTxRequest.Marshal(b, m, deterministic)
}
func (m *NewUnsignedTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUnsignedTxRequest.Merge(m, src)
}
func (m *NewUnsignedTxRequest) XXX_Size() int {
	return xxx_messageInfo_NewUnsignedTxRequest.Size(m)
}
func (m *NewUnsignedTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUnsignedTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUnsignedTxRequest proto.InternalMessageInfo

func (m *NewUnsignedTxRequest) GetReceiver() []byte {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *NewUnsignedTxRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *NewUnsignedTxRequest) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

type NewUnsignedTxReply struct {
	Raw                  []byte   `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUnsignedTxReply) Reset()         { *m = NewUnsignedTxReply{} }
func (m *NewUnsignedTxReply) String() string { return proto.CompactTextString(m) }
func (*NewUnsignedTxReply) ProtoMessage()    {}
func (*NewUnsignedTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *NewUnsignedTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUnsignedTxReply.Unmarshal(m, b)
}
func (m *NewUnsignedTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUnsignedTxReply.Marshal(b, m, deterministic)
}
func (m *NewUnsignedTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUnsignedTxReply.Merge(m, src)
}
func (m *NewUnsignedTxReply) XXX_Size() int {
	return xxx_messageInfo_NewUnsignedTxReply.Size(m)
}
func (m *NewUnsignedTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUnsignedTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewUnsignedTxReply proto.InternalMessageInfo

func (m *NewUnsignedTxReply) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type BroadcastTxRequest struct {
	WalletId             string   `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastTxRequest) Reset()         { *m = BroadcastTxRequest{} }
func (m *BroadcastTxRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastTxRequest) ProtoMessage()    {}
func (*BroadcastTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *BroadcastTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastTxRequest.Unmarshal(m, b)
}
func (m *BroadcastTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastTxRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastTxRequest.Merge(m, src)
}
func (m *BroadcastTxRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastTxRequest.Size(m)
}
func (m *BroadcastTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastTxRequest proto.InternalMessageInfo

func (m *BroadcastTxRequest) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

func (m *BroadcastTxRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type BroadcastTxReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastTxReply) Reset()         { *m = BroadcastTxReply{} }
func (m *BroadcastTxReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastTxReply) ProtoMessage()    {}
func (*BroadcastTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *BroadcastTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastTxReply.Unmarshal(m, b)
}
func (m *BroadcastTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastTxReply.Marshal(b, m, deterministic)
}
func (m *BroadcastTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastTxReply.Merge(m, src)
}
func (m *BroadcastTxReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastTxReply.Size(m)
}
func (m *BroadcastTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastTxReply proto.InternalMessageInfo

func (m *BroadcastTxReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type HealthCheckRequest struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type HealthCheckReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckReply) Reset()         { *m = HealthCheckReply{} }
func (m *HealthCheckReply) String() string { return proto.CompactTextString(m) }
func (*HealthCheckReply) ProtoMessage()    {}
func (*HealthCheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *HealthCheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckReply.Unmarshal(m, b)
}
func (m *HealthCheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckReply.Marshal(b, m, deterministic)
}
func (m *HealthCheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckReply.Merge(m, src)
}
func (m *HealthCheckReply) XXX_Size() int {
	return xxx_messageInfo_HealthCheckReply.Size(m)
}
func (m *HealthCheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckReply proto.InternalMessageInfo

func (m *HealthCheckReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*NewMultiSigRequest)(nil), "service.NewMultiSigRequest")
	proto.RegisterType((*NewMultiSigReply)(nil), "service.NewMultiSigReply")
	proto.RegisterType((*NewUnsignedTxRequest)(nil), "service.NewUnsignedTxRequest")
	proto.RegisterType((*NewUnsignedTxReply)(nil), "service.NewUnsignedTxReply")
	proto.RegisterType((*BroadcastTxRequest)(nil), "service.BroadcastTxRequest")
	proto.RegisterType((*BroadcastTxReply)(nil), "service.BroadcastTxReply")
	proto.RegisterType((*HealthCheckRequest)(nil), "service.HealthCheckRequest")
	proto.RegisterType((*HealthCheckReply)(nil), "service.HealthCheckReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcd, 0x8e, 0xda, 0x30,
	0x14, 0x85, 0x87, 0x49, 0xc5, 0xb4, 0x97, 0x8c, 0x14, 0x59, 0xd5, 0x28, 0x65, 0x54, 0x09, 0x79,
	0x81, 0x50, 0x17, 0x2c, 0xda, 0x37, 0x68, 0x17, 0xd0, 0x4a, 0xb0, 0x08, 0x2d, 0x7b, 0x93, 0xdc,
	0x42, 0x8a, 0xf3, 0x53, 0xdb, 0x21, 0xe5, 0xc9, 0xfa, 0x7a, 0x95, 0x8d, 0x83, 0x6c, 0xd2, 0xaa,
	0x3b, 0x1f, 0x6c, 0xbe, 0x73, 0x7c, 0xae, 0x03, 0x8f, 0x12, 0xc5, 0x29, 0x4f, 0x71, 0x5e, 0x8b,
	0x4a, 0x55, 0xe4, 0xc1, 0x4a, 0xba, 0x04, 0xb2, 0xc6, 0x76, 0xd5, 0x70, 0x95, 0x6f, 0xf2, 0x7d,
	0x82, 0x3f, 0x1b, 0x94, 0x8a, 0xc4, 0xf0, 0x50, 0xa2, 0x6a, 0x2b, 0x71, 0x8c, 0x07, 0x93, 0xc1,
	0xec, 0x55, 0xd2, 0x49, 0xbd, 0x53, 0x37, 0xbb, 0x23, 0x9e, 0x65, 0x7c, 0x3f, 0x09, 0x66, 0x61,
	0xd2, 0x49, 0xfa, 0x03, 0x22, 0x8f, 0x54, 0xf3, 0x33, 0xa1, 0x10, 0x0a, 0xcc, 0x10, 0x8b, 0x4d,
	0x2a, 0xf2, 0x5a, 0x59, 0x98, 0xf7, 0x9b, 0x26, 0xb2, 0x2c, 0x13, 0x28, 0x35, 0xd1, 0x78, 0x59,
	0xe9, 0x7a, 0x05, 0xbe, 0xd7, 0x77, 0x78, 0xbd, 0xc6, 0xf6, 0x5b, 0x29, 0xf3, 0x7d, 0x89, 0xd9,
	0xd7, 0x5f, 0x5d, 0xee, 0x31, 0xbc, 0x14, 0x98, 0x62, 0x7e, 0x42, 0x61, 0xbc, 0xc2, 0xe4, 0xaa,
	0xc9, 0x13, 0x0c, 0x59, 0x51, 0x35, 0xa5, 0x32, 0x36, 0x41, 0x62, 0x95, 0xfe, 0x4f, 0xcb, 0x38,
	0x47, 0xf5, 0x39, 0x8b, 0x03, 0x13, 0xe0, 0xaa, 0xe9, 0xd4, 0xb4, 0xe3, 0xfa, 0xe8, 0x5b, 0x45,
	0x10, 0x08, 0xd6, 0x5a, 0x03, 0xbd, 0xa4, 0x5f, 0x80, 0x7c, 0x14, 0x15, 0xcb, 0x52, 0x26, 0x95,
	0x97, 0xe6, 0x4a, 0x1e, 0xf8, 0x64, 0x7d, 0xb7, 0x02, 0xa5, 0x64, 0x7b, 0x34, 0x71, 0xc2, 0xa4,
	0x93, 0x74, 0x0a, 0x91, 0xc7, 0xd2, 0x8e, 0x04, 0x5e, 0x64, 0x4c, 0x31, 0x4b, 0x31, 0x6b, 0x3a,
	0x07, 0xb2, 0x44, 0xc6, 0xd5, 0xe1, 0xd3, 0x01, 0xd3, 0xe3, 0x7f, 0x27, 0x47, 0xdf, 0x41, 0xe4,
	0x9d, 0xd7, 0xdc, 0x27, 0x18, 0x4a, 0xc5, 0x54, 0x23, 0xed, 0x61, 0xab, 0xde, 0xff, 0xbe, 0x87,
	0xd1, 0xb6, 0xe1, 0x35, 0x16, 0x5b, 0xd6, 0x70, 0x45, 0x16, 0x30, 0x72, 0x66, 0x4b, 0x9e, 0xe7,
	0xdd, 0x6b, 0xea, 0xbf, 0x9d, 0xf1, 0x9b, 0xbf, 0x6f, 0xd6, 0xfc, 0x4c, 0xef, 0xc8, 0x0a, 0x1e,
	0xbd, 0x42, 0xc9, 0x5b, 0xf7, 0x74, 0x6f, 0xa0, 0xe3, 0xe7, 0x7f, 0x6d, 0x5f, 0x70, 0x0b, 0x18,
	0x39, 0x5d, 0x39, 0xb9, 0xfa, 0xd3, 0x70, 0x72, 0xdd, 0xd6, 0x7b, 0x01, 0x39, 0xe5, 0x38, 0xa0,
	0x7e, 0xc5, 0x0e, 0xe8, 0xb6, 0x4f, 0x7a, 0xb7, 0x1b, 0x9a, 0xef, 0xeb, 0xc3, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0xfa, 0xa8, 0xa0, 0x70, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VulpemVaultClient is the client API for VulpemVault service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VulpemVaultClient interface {
	NewMultiSig(ctx context.Context, in *NewMultiSigRequest, opts ...grpc.CallOption) (*NewMultiSigReply, error)
	NewUnsignedTx(ctx context.Context, in *NewUnsignedTxRequest, opts ...grpc.CallOption) (*NewUnsignedTxReply, error)
	BroadcastTx(ctx context.Context, in *BroadcastTxRequest, opts ...grpc.CallOption) (*BroadcastTxReply, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckReply, error)
}

type vulpemVaultClient struct {
	cc *grpc.ClientConn
}

func NewVulpemVaultClient(cc *grpc.ClientConn) VulpemVaultClient {
	return &vulpemVaultClient{cc}
}

func (c *vulpemVaultClient) NewMultiSig(ctx context.Context, in *NewMultiSigRequest, opts ...grpc.CallOption) (*NewMultiSigReply, error) {
	out := new(NewMultiSigReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/NewMultiSig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) NewUnsignedTx(ctx context.Context, in *NewUnsignedTxRequest, opts ...grpc.CallOption) (*NewUnsignedTxReply, error) {
	out := new(NewUnsignedTxReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/NewUnsignedTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) BroadcastTx(ctx context.Context, in *BroadcastTxRequest, opts ...grpc.CallOption) (*BroadcastTxReply, error) {
	out := new(BroadcastTxReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/BroadcastTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckReply, error) {
	out := new(HealthCheckReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VulpemVaultServer is the server API for VulpemVault service.
type VulpemVaultServer interface {
	NewMultiSig(context.Context, *NewMultiSigRequest) (*NewMultiSigReply, error)
	NewUnsignedTx(context.Context, *NewUnsignedTxRequest) (*NewUnsignedTxReply, error)
	BroadcastTx(context.Context, *BroadcastTxRequest) (*BroadcastTxReply, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckReply, error)
}

func RegisterVulpemVaultServer(s *grpc.Server, srv VulpemVaultServer) {
	s.RegisterService(&_VulpemVault_serviceDesc, srv)
}

func _VulpemVault_NewMultiSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMultiSigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).NewMultiSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/NewMultiSig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).NewMultiSig(ctx, req.(*NewMultiSigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_NewUnsignedTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUnsignedTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).NewUnsignedTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/NewUnsignedTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).NewUnsignedTx(ctx, req.(*NewUnsignedTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_BroadcastTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).BroadcastTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/BroadcastTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).BroadcastTx(ctx, req.(*BroadcastTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VulpemVault_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.VulpemVault",
	HandlerType: (*VulpemVaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewMultiSig",
			Handler:    _VulpemVault_NewMultiSig_Handler,
		},
		{
			MethodName: "NewUnsignedTx",
			Handler:    _VulpemVault_NewUnsignedTx_Handler,
		},
		{
			MethodName: "BroadcastTx",
			Handler:    _VulpemVault_BroadcastTx_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _VulpemVault_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
