// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewMultiSigRequest struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Pubkeys              [][]byte `protobuf:"bytes,2,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	SatoshiLimit         uint64   `protobuf:"varint,3,opt,name=satoshiLimit,proto3" json:"satoshiLimit,omitempty"`
	TimeRange            uint64   `protobuf:"varint,4,opt,name=timeRange,proto3" json:"timeRange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMultiSigRequest) Reset()         { *m = NewMultiSigRequest{} }
func (m *NewMultiSigRequest) String() string { return proto.CompactTextString(m) }
func (*NewMultiSigRequest) ProtoMessage()    {}
func (*NewMultiSigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *NewMultiSigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMultiSigRequest.Unmarshal(m, b)
}
func (m *NewMultiSigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMultiSigRequest.Marshal(b, m, deterministic)
}
func (m *NewMultiSigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMultiSigRequest.Merge(m, src)
}
func (m *NewMultiSigRequest) XXX_Size() int {
	return xxx_messageInfo_NewMultiSigRequest.Size(m)
}
func (m *NewMultiSigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMultiSigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewMultiSigRequest proto.InternalMessageInfo

func (m *NewMultiSigRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NewMultiSigRequest) GetPubkeys() [][]byte {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

func (m *NewMultiSigRequest) GetSatoshiLimit() uint64 {
	if m != nil {
		return m.SatoshiLimit
	}
	return 0
}

func (m *NewMultiSigRequest) GetTimeRange() uint64 {
	if m != nil {
		return m.TimeRange
	}
	return 0
}

type NewMultiSigReply struct {
	RedeemScript         string   `protobuf:"bytes,1,opt,name=redeemScript,proto3" json:"redeemScript,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Pubkeys              [][]byte `protobuf:"bytes,3,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMultiSigReply) Reset()         { *m = NewMultiSigReply{} }
func (m *NewMultiSigReply) String() string { return proto.CompactTextString(m) }
func (*NewMultiSigReply) ProtoMessage()    {}
func (*NewMultiSigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *NewMultiSigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMultiSigReply.Unmarshal(m, b)
}
func (m *NewMultiSigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMultiSigReply.Marshal(b, m, deterministic)
}
func (m *NewMultiSigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMultiSigReply.Merge(m, src)
}
func (m *NewMultiSigReply) XXX_Size() int {
	return xxx_messageInfo_NewMultiSigReply.Size(m)
}
func (m *NewMultiSigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMultiSigReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewMultiSigReply proto.InternalMessageInfo

func (m *NewMultiSigReply) GetRedeemScript() string {
	if m != nil {
		return m.RedeemScript
	}
	return ""
}

func (m *NewMultiSigReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewMultiSigReply) GetPubkeys() [][]byte {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

type SetupMfaRequest struct {
	WalletId             string   `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupMfaRequest) Reset()         { *m = SetupMfaRequest{} }
func (m *SetupMfaRequest) String() string { return proto.CompactTextString(m) }
func (*SetupMfaRequest) ProtoMessage()    {}
func (*SetupMfaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *SetupMfaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupMfaRequest.Unmarshal(m, b)
}
func (m *SetupMfaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupMfaRequest.Marshal(b, m, deterministic)
}
func (m *SetupMfaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupMfaRequest.Merge(m, src)
}
func (m *SetupMfaRequest) XXX_Size() int {
	return xxx_messageInfo_SetupMfaRequest.Size(m)
}
func (m *SetupMfaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupMfaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetupMfaRequest proto.InternalMessageInfo

func (m *SetupMfaRequest) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

type SetupMfaReply struct {
	Barcode              string   `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupMfaReply) Reset()         { *m = SetupMfaReply{} }
func (m *SetupMfaReply) String() string { return proto.CompactTextString(m) }
func (*SetupMfaReply) ProtoMessage()    {}
func (*SetupMfaReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *SetupMfaReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupMfaReply.Unmarshal(m, b)
}
func (m *SetupMfaReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupMfaReply.Marshal(b, m, deterministic)
}
func (m *SetupMfaReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupMfaReply.Merge(m, src)
}
func (m *SetupMfaReply) XXX_Size() int {
	return xxx_messageInfo_SetupMfaReply.Size(m)
}
func (m *SetupMfaReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupMfaReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetupMfaReply proto.InternalMessageInfo

func (m *SetupMfaReply) GetBarcode() string {
	if m != nil {
		return m.Barcode
	}
	return ""
}

func (m *SetupMfaReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GenerateOtpRequest struct {
	WalletId             string   `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateOtpRequest) Reset()         { *m = GenerateOtpRequest{} }
func (m *GenerateOtpRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateOtpRequest) ProtoMessage()    {}
func (*GenerateOtpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GenerateOtpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateOtpRequest.Unmarshal(m, b)
}
func (m *GenerateOtpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateOtpRequest.Marshal(b, m, deterministic)
}
func (m *GenerateOtpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateOtpRequest.Merge(m, src)
}
func (m *GenerateOtpRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateOtpRequest.Size(m)
}
func (m *GenerateOtpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateOtpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateOtpRequest proto.InternalMessageInfo

func (m *GenerateOtpRequest) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

type GenerateOtpReply struct {
	Otp                  uint64   `protobuf:"varint,1,opt,name=otp,proto3" json:"otp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateOtpReply) Reset()         { *m = GenerateOtpReply{} }
func (m *GenerateOtpReply) String() string { return proto.CompactTextString(m) }
func (*GenerateOtpReply) ProtoMessage()    {}
func (*GenerateOtpReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *GenerateOtpReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateOtpReply.Unmarshal(m, b)
}
func (m *GenerateOtpReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateOtpReply.Marshal(b, m, deterministic)
}
func (m *GenerateOtpReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateOtpReply.Merge(m, src)
}
func (m *GenerateOtpReply) XXX_Size() int {
	return xxx_messageInfo_GenerateOtpReply.Size(m)
}
func (m *GenerateOtpReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateOtpReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateOtpReply proto.InternalMessageInfo

func (m *GenerateOtpReply) GetOtp() uint64 {
	if m != nil {
		return m.Otp
	}
	return 0
}

type VerifyOtpRequest struct {
	WalletId             string   `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Otp                  uint64   `protobuf:"varint,2,opt,name=otp,proto3" json:"otp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOtpRequest) Reset()         { *m = VerifyOtpRequest{} }
func (m *VerifyOtpRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyOtpRequest) ProtoMessage()    {}
func (*VerifyOtpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *VerifyOtpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOtpRequest.Unmarshal(m, b)
}
func (m *VerifyOtpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOtpRequest.Marshal(b, m, deterministic)
}
func (m *VerifyOtpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOtpRequest.Merge(m, src)
}
func (m *VerifyOtpRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyOtpRequest.Size(m)
}
func (m *VerifyOtpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOtpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOtpRequest proto.InternalMessageInfo

func (m *VerifyOtpRequest) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

func (m *VerifyOtpRequest) GetOtp() uint64 {
	if m != nil {
		return m.Otp
	}
	return 0
}

type VerifyOtpReply struct {
	Verified             bool     `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOtpReply) Reset()         { *m = VerifyOtpReply{} }
func (m *VerifyOtpReply) String() string { return proto.CompactTextString(m) }
func (*VerifyOtpReply) ProtoMessage()    {}
func (*VerifyOtpReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *VerifyOtpReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOtpReply.Unmarshal(m, b)
}
func (m *VerifyOtpReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOtpReply.Marshal(b, m, deterministic)
}
func (m *VerifyOtpReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOtpReply.Merge(m, src)
}
func (m *VerifyOtpReply) XXX_Size() int {
	return xxx_messageInfo_VerifyOtpReply.Size(m)
}
func (m *VerifyOtpReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOtpReply.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOtpReply proto.InternalMessageInfo

func (m *VerifyOtpReply) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type NewUnsignedTxRequest struct {
	Receiver             []byte   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	WalletId             string   `protobuf:"bytes,3,opt,name=walletId,proto3" json:"walletId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUnsignedTxRequest) Reset()         { *m = NewUnsignedTxRequest{} }
func (m *NewUnsignedTxRequest) String() string { return proto.CompactTextString(m) }
func (*NewUnsignedTxRequest) ProtoMessage()    {}
func (*NewUnsignedTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *NewUnsignedTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUnsignedTxRequest.Unmarshal(m, b)
}
func (m *NewUnsignedTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUnsignedTxRequest.Marshal(b, m, deterministic)
}
func (m *NewUnsignedTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUnsignedTxRequest.Merge(m, src)
}
func (m *NewUnsignedTxRequest) XXX_Size() int {
	return xxx_messageInfo_NewUnsignedTxRequest.Size(m)
}
func (m *NewUnsignedTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUnsignedTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUnsignedTxRequest proto.InternalMessageInfo

func (m *NewUnsignedTxRequest) GetReceiver() []byte {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *NewUnsignedTxRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *NewUnsignedTxRequest) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

type NewUnsignedTxReply struct {
	Raw                  []byte   `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUnsignedTxReply) Reset()         { *m = NewUnsignedTxReply{} }
func (m *NewUnsignedTxReply) String() string { return proto.CompactTextString(m) }
func (*NewUnsignedTxReply) ProtoMessage()    {}
func (*NewUnsignedTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *NewUnsignedTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUnsignedTxReply.Unmarshal(m, b)
}
func (m *NewUnsignedTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUnsignedTxReply.Marshal(b, m, deterministic)
}
func (m *NewUnsignedTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUnsignedTxReply.Merge(m, src)
}
func (m *NewUnsignedTxReply) XXX_Size() int {
	return xxx_messageInfo_NewUnsignedTxReply.Size(m)
}
func (m *NewUnsignedTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUnsignedTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewUnsignedTxReply proto.InternalMessageInfo

func (m *NewUnsignedTxReply) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type BroadcastTxRequest struct {
	WalletId             string   `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Otp                  uint64   `protobuf:"varint,3,opt,name=otp,proto3" json:"otp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastTxRequest) Reset()         { *m = BroadcastTxRequest{} }
func (m *BroadcastTxRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastTxRequest) ProtoMessage()    {}
func (*BroadcastTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *BroadcastTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastTxRequest.Unmarshal(m, b)
}
func (m *BroadcastTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastTxRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastTxRequest.Merge(m, src)
}
func (m *BroadcastTxRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastTxRequest.Size(m)
}
func (m *BroadcastTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastTxRequest proto.InternalMessageInfo

func (m *BroadcastTxRequest) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

func (m *BroadcastTxRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *BroadcastTxRequest) GetOtp() uint64 {
	if m != nil {
		return m.Otp
	}
	return 0
}

type BroadcastTxReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastTxReply) Reset()         { *m = BroadcastTxReply{} }
func (m *BroadcastTxReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastTxReply) ProtoMessage()    {}
func (*BroadcastTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *BroadcastTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastTxReply.Unmarshal(m, b)
}
func (m *BroadcastTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastTxReply.Marshal(b, m, deterministic)
}
func (m *BroadcastTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastTxReply.Merge(m, src)
}
func (m *BroadcastTxReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastTxReply.Size(m)
}
func (m *BroadcastTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastTxReply proto.InternalMessageInfo

func (m *BroadcastTxReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Service) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Service) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type HealthCheckReply struct {
	Status               string     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Services             []*Service `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HealthCheckReply) Reset()         { *m = HealthCheckReply{} }
func (m *HealthCheckReply) String() string { return proto.CompactTextString(m) }
func (*HealthCheckReply) ProtoMessage()    {}
func (*HealthCheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *HealthCheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckReply.Unmarshal(m, b)
}
func (m *HealthCheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckReply.Marshal(b, m, deterministic)
}
func (m *HealthCheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckReply.Merge(m, src)
}
func (m *HealthCheckReply) XXX_Size() int {
	return xxx_messageInfo_HealthCheckReply.Size(m)
}
func (m *HealthCheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckReply proto.InternalMessageInfo

func (m *HealthCheckReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HealthCheckReply) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*NewMultiSigRequest)(nil), "service.NewMultiSigRequest")
	proto.RegisterType((*NewMultiSigReply)(nil), "service.NewMultiSigReply")
	proto.RegisterType((*SetupMfaRequest)(nil), "service.SetupMfaRequest")
	proto.RegisterType((*SetupMfaReply)(nil), "service.SetupMfaReply")
	proto.RegisterType((*GenerateOtpRequest)(nil), "service.GenerateOtpRequest")
	proto.RegisterType((*GenerateOtpReply)(nil), "service.GenerateOtpReply")
	proto.RegisterType((*VerifyOtpRequest)(nil), "service.VerifyOtpRequest")
	proto.RegisterType((*VerifyOtpReply)(nil), "service.VerifyOtpReply")
	proto.RegisterType((*NewUnsignedTxRequest)(nil), "service.NewUnsignedTxRequest")
	proto.RegisterType((*NewUnsignedTxReply)(nil), "service.NewUnsignedTxReply")
	proto.RegisterType((*BroadcastTxRequest)(nil), "service.BroadcastTxRequest")
	proto.RegisterType((*BroadcastTxReply)(nil), "service.BroadcastTxReply")
	proto.RegisterType((*HealthCheckRequest)(nil), "service.HealthCheckRequest")
	proto.RegisterType((*Service)(nil), "service.Service")
	proto.RegisterType((*HealthCheckReply)(nil), "service.HealthCheckReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x6f, 0x13, 0x3f,
	0x10, 0x6d, 0xba, 0xf9, 0x35, 0xc9, 0x24, 0xfd, 0xb1, 0xb2, 0xaa, 0xb2, 0xa4, 0x20, 0x55, 0x16,
	0xaa, 0x7a, 0x28, 0x15, 0x2a, 0x47, 0x24, 0xc4, 0xc7, 0xa1, 0x20, 0xd1, 0x22, 0x39, 0x50, 0x71,
	0xe0, 0xe2, 0x66, 0xa7, 0xa9, 0xe9, 0x7e, 0x61, 0x7b, 0x1b, 0x72, 0xe6, 0xc6, 0x5f, 0x8d, 0xbc,
	0xeb, 0xdd, 0xd8, 0x49, 0x2b, 0xf5, 0xe6, 0x67, 0x7b, 0xde, 0xbc, 0xb1, 0xde, 0xdb, 0x85, 0x6d,
	0x85, 0xf2, 0x56, 0x4c, 0xf1, 0xb8, 0x90, 0xb9, 0xce, 0x49, 0xcf, 0x42, 0xfa, 0xb7, 0x03, 0xe4,
	0x1c, 0xe7, 0x67, 0x65, 0xa2, 0xc5, 0x44, 0xcc, 0x18, 0xfe, 0x2a, 0x51, 0x69, 0x12, 0x41, 0x2f,
	0x43, 0x3d, 0xcf, 0xe5, 0x4d, 0xd4, 0xd9, 0xef, 0x1c, 0x0e, 0x58, 0x03, 0xcd, 0x49, 0x51, 0x5e,
	0xde, 0xe0, 0x42, 0x45, 0x9b, 0xfb, 0xc1, 0xe1, 0x88, 0x35, 0x90, 0x50, 0x18, 0x29, 0xae, 0x73,
	0x75, 0x2d, 0x3e, 0x8b, 0x54, 0xe8, 0x28, 0xd8, 0xef, 0x1c, 0x76, 0x99, 0xb7, 0x47, 0x9e, 0xc2,
	0x40, 0x8b, 0x14, 0x19, 0xcf, 0x66, 0x18, 0x75, 0xab, 0x0b, 0xcb, 0x0d, 0xfa, 0x13, 0x42, 0x4f,
	0x4b, 0x91, 0x2c, 0x0c, 0xab, 0xc4, 0x18, 0x31, 0x9d, 0x4c, 0xa5, 0x28, 0xb4, 0x95, 0xe3, 0xed,
	0x19, 0x4d, 0x3c, 0x8e, 0x25, 0x2a, 0xa3, 0xa9, 0x52, 0x6b, 0xa1, 0xab, 0x36, 0xf0, 0xd4, 0xd2,
	0x17, 0xf0, 0x68, 0x82, 0xba, 0x2c, 0xce, 0xae, 0x78, 0x33, 0xf4, 0x18, 0xfa, 0x73, 0x9e, 0x24,
	0xa8, 0x3f, 0xc5, 0xb6, 0x4d, 0x8b, 0xe9, 0x6b, 0xd8, 0x5e, 0x5e, 0x37, 0xba, 0x22, 0xe8, 0x5d,
	0x72, 0x39, 0xcd, 0x63, 0x6c, 0x5e, 0xc8, 0x42, 0x12, 0x42, 0x50, 0xca, 0xc4, 0x2a, 0x31, 0x4b,
	0xfa, 0x12, 0xc8, 0x29, 0x66, 0x28, 0xb9, 0xc6, 0x2f, 0xba, 0x78, 0x48, 0xbb, 0xe7, 0x10, 0x7a,
	0x15, 0xa6, 0x63, 0x08, 0x41, 0xae, 0x8b, 0xea, 0x6a, 0x97, 0x99, 0x25, 0x7d, 0x0b, 0xe1, 0x05,
	0x4a, 0x71, 0xb5, 0x78, 0x18, 0x6b, 0xc3, 0xb0, 0xb9, 0x64, 0x38, 0x82, 0xff, 0x1d, 0x06, 0xd3,
	0x65, 0x0c, 0xfd, 0x5b, 0xb3, 0x23, 0xb0, 0xae, 0xef, 0xb3, 0x16, 0xd3, 0x2b, 0xd8, 0x39, 0xc7,
	0xf9, 0xb7, 0x4c, 0x89, 0x59, 0x86, 0xf1, 0xd7, 0xdf, 0x4e, 0x4f, 0x89, 0x53, 0x14, 0xb7, 0x28,
	0xab, 0x9a, 0x11, 0x6b, 0x31, 0xd9, 0x85, 0x2d, 0x9e, 0xe6, 0x65, 0xa6, 0xab, 0xb6, 0x01, 0xb3,
	0xc8, 0xd3, 0x19, 0xac, 0x4c, 0x7f, 0x50, 0x79, 0xd2, 0xed, 0x63, 0xe7, 0x97, 0x7c, 0x6e, 0x1b,
	0x98, 0x25, 0xfd, 0x01, 0xe4, 0xbd, 0xcc, 0x79, 0x3c, 0xe5, 0x4a, 0x7b, 0x6a, 0xee, 0x7d, 0x81,
	0x08, 0x7a, 0x29, 0x2a, 0xc5, 0x67, 0x58, 0xc9, 0x19, 0xb1, 0x06, 0x36, 0x6f, 0x13, 0x2c, 0xdf,
	0xe6, 0x00, 0x42, 0x8f, 0xdd, 0x68, 0x20, 0xd0, 0x8d, 0xb9, 0xe6, 0x96, 0xb7, 0x5a, 0xd3, 0x1d,
	0x20, 0x1f, 0x91, 0x27, 0xfa, 0xfa, 0xc3, 0x35, 0x4e, 0x6f, 0xac, 0x0a, 0x8a, 0xd0, 0x9b, 0xd4,
	0x19, 0x33, 0x45, 0x19, 0x4f, 0x1b, 0x9f, 0x54, 0x6b, 0x37, 0x60, 0x9b, 0x7e, 0xc0, 0x76, 0x61,
	0x4b, 0x69, 0xae, 0x4b, 0x65, 0x9f, 0xc5, 0x22, 0xb2, 0x03, 0xff, 0xa1, 0x94, 0xb9, 0xac, 0x62,
	0x33, 0x60, 0x35, 0xa0, 0xdf, 0x21, 0xf4, 0x9a, 0x1b, 0x91, 0x4b, 0x86, 0x8e, 0xc7, 0x70, 0x04,
	0x7d, 0x1b, 0xfb, 0x3a, 0xbb, 0xc3, 0x93, 0xf0, 0xb8, 0xf9, 0x2c, 0x58, 0xad, 0xac, 0xbd, 0x71,
	0xf2, 0xa7, 0x0b, 0xc3, 0x8b, 0x32, 0x29, 0x30, 0xbd, 0xe0, 0x65, 0xa2, 0xc9, 0x29, 0x0c, 0x9d,
	0x70, 0x92, 0xbd, 0xb6, 0x74, 0xfd, 0xf3, 0x31, 0x7e, 0x72, 0xf7, 0x61, 0x91, 0x2c, 0xe8, 0x06,
	0x79, 0x03, 0xfd, 0x26, 0x4a, 0x24, 0x72, 0x04, 0x78, 0x61, 0x1c, 0xef, 0xde, 0x71, 0x52, 0xd7,
	0x9f, 0xc2, 0xd0, 0xc9, 0x86, 0x23, 0x64, 0x3d, 0x63, 0x8e, 0x90, 0xd5, 0x38, 0xd1, 0x0d, 0xf2,
	0x0e, 0x06, 0xad, 0xf9, 0xc9, 0xf2, 0xe6, 0x6a, 0xa4, 0xc6, 0x8f, 0xef, 0x3a, 0xaa, 0x29, 0xce,
	0x60, 0xdb, 0x73, 0x2a, 0x79, 0xe6, 0x4e, 0xbe, 0x96, 0x94, 0xf1, 0xde, 0x7d, 0xc7, 0xed, 0x68,
	0x8e, 0xe5, 0x9c, 0xd1, 0xd6, 0x6d, 0xee, 0x8c, 0xb6, 0xea, 0xd2, 0x9a, 0xc8, 0xb1, 0x85, 0x43,
	0xb4, 0xee, 0x54, 0x87, 0x68, 0xd5, 0x49, 0x74, 0xe3, 0x72, 0xab, 0xfa, 0x5f, 0xbc, 0xfa, 0x17,
	0x00, 0x00, 0xff, 0xff, 0xae, 0x0d, 0x14, 0x10, 0x40, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VulpemVaultClient is the client API for VulpemVault service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VulpemVaultClient interface {
	NewMultiSig(ctx context.Context, in *NewMultiSigRequest, opts ...grpc.CallOption) (*NewMultiSigReply, error)
	SetupMfa(ctx context.Context, in *SetupMfaRequest, opts ...grpc.CallOption) (*SetupMfaReply, error)
	GenerateOtp(ctx context.Context, in *GenerateOtpRequest, opts ...grpc.CallOption) (*GenerateOtpReply, error)
	VerifyOtp(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*VerifyOtpReply, error)
	NewUnsignedTx(ctx context.Context, in *NewUnsignedTxRequest, opts ...grpc.CallOption) (*NewUnsignedTxReply, error)
	BroadcastTx(ctx context.Context, in *BroadcastTxRequest, opts ...grpc.CallOption) (*BroadcastTxReply, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckReply, error)
}

type vulpemVaultClient struct {
	cc *grpc.ClientConn
}

func NewVulpemVaultClient(cc *grpc.ClientConn) VulpemVaultClient {
	return &vulpemVaultClient{cc}
}

func (c *vulpemVaultClient) NewMultiSig(ctx context.Context, in *NewMultiSigRequest, opts ...grpc.CallOption) (*NewMultiSigReply, error) {
	out := new(NewMultiSigReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/NewMultiSig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) SetupMfa(ctx context.Context, in *SetupMfaRequest, opts ...grpc.CallOption) (*SetupMfaReply, error) {
	out := new(SetupMfaReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/SetupMfa", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) GenerateOtp(ctx context.Context, in *GenerateOtpRequest, opts ...grpc.CallOption) (*GenerateOtpReply, error) {
	out := new(GenerateOtpReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/GenerateOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) VerifyOtp(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*VerifyOtpReply, error) {
	out := new(VerifyOtpReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/VerifyOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) NewUnsignedTx(ctx context.Context, in *NewUnsignedTxRequest, opts ...grpc.CallOption) (*NewUnsignedTxReply, error) {
	out := new(NewUnsignedTxReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/NewUnsignedTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) BroadcastTx(ctx context.Context, in *BroadcastTxRequest, opts ...grpc.CallOption) (*BroadcastTxReply, error) {
	out := new(BroadcastTxReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/BroadcastTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulpemVaultClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckReply, error) {
	out := new(HealthCheckReply)
	err := c.cc.Invoke(ctx, "/service.VulpemVault/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VulpemVaultServer is the server API for VulpemVault service.
type VulpemVaultServer interface {
	NewMultiSig(context.Context, *NewMultiSigRequest) (*NewMultiSigReply, error)
	SetupMfa(context.Context, *SetupMfaRequest) (*SetupMfaReply, error)
	GenerateOtp(context.Context, *GenerateOtpRequest) (*GenerateOtpReply, error)
	VerifyOtp(context.Context, *VerifyOtpRequest) (*VerifyOtpReply, error)
	NewUnsignedTx(context.Context, *NewUnsignedTxRequest) (*NewUnsignedTxReply, error)
	BroadcastTx(context.Context, *BroadcastTxRequest) (*BroadcastTxReply, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckReply, error)
}

func RegisterVulpemVaultServer(s *grpc.Server, srv VulpemVaultServer) {
	s.RegisterService(&_VulpemVault_serviceDesc, srv)
}

func _VulpemVault_NewMultiSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMultiSigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).NewMultiSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/NewMultiSig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).NewMultiSig(ctx, req.(*NewMultiSigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_SetupMfa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupMfaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).SetupMfa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/SetupMfa",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).SetupMfa(ctx, req.(*SetupMfaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_GenerateOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).GenerateOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/GenerateOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).GenerateOtp(ctx, req.(*GenerateOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_VerifyOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).VerifyOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/VerifyOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).VerifyOtp(ctx, req.(*VerifyOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_NewUnsignedTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUnsignedTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).NewUnsignedTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/NewUnsignedTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).NewUnsignedTx(ctx, req.(*NewUnsignedTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_BroadcastTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).BroadcastTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/BroadcastTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).BroadcastTx(ctx, req.(*BroadcastTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulpemVault_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulpemVaultServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.VulpemVault/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulpemVaultServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VulpemVault_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.VulpemVault",
	HandlerType: (*VulpemVaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewMultiSig",
			Handler:    _VulpemVault_NewMultiSig_Handler,
		},
		{
			MethodName: "SetupMfa",
			Handler:    _VulpemVault_SetupMfa_Handler,
		},
		{
			MethodName: "GenerateOtp",
			Handler:    _VulpemVault_GenerateOtp_Handler,
		},
		{
			MethodName: "VerifyOtp",
			Handler:    _VulpemVault_VerifyOtp_Handler,
		},
		{
			MethodName: "NewUnsignedTx",
			Handler:    _VulpemVault_NewUnsignedTx_Handler,
		},
		{
			MethodName: "BroadcastTx",
			Handler:    _VulpemVault_BroadcastTx_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _VulpemVault_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
